apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: traefik
            namespace: traefik
            chart: traefik
            repoURL: https://traefik.github.io/charts
            version: 37.2.0

          - name: cert-manager
            namespace: cert-manager
            chart: cert-manager
            repoURL: https://charts.jetstack.io
            version: v1.16.1

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      sources:
        - repoURL: '{{repoURL}}'
          chart: '{{chart}}'
          targetRevision: '{{version}}'
          helm:
            releaseName: '{{name}}'
            valueFiles:
              - $values/apps/{{name}}/values.yaml
        - repoURL: https://github.com/tomas-rojo/homelab-gitops.git
          targetRevision: main
          ref: values
